In [31]:
import numpy as np

In [32]:
# array creation
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


In [33]:
# array indexing
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[4])
# negative indexing 
print(arr[-1])
print(arr[-2])

10
20
30
50
50
40


In [34]:
arr=np.array([10,20,30,40,50])
print(arr[3])
print(arr[-1])

40
50


In [35]:
# Array Slicing
# start sa value
arr=np.array([10,20,30,40,50])
print(arr[:3])
# end sa value
print(arr[2:])
# negative slice
print(arr[-3:])
# type checking
print(arr.dtype)


[10 20 30]
[30 40 50]
[30 40 50]
int64


In [36]:
arr_float = np.array([10.5, 20.5, 30.5])
# data type check
print(arr_float)
print(arr_float.dtype)

[10.5 20.5 30.5]
float64


In [37]:
# Copy vs View
# arr ki copy create karke us ma value chnage karna
# Independent array banata hai.
arr = np.array([10, 20, 30, 40, 50])

copy_arr = arr.copy()

copy_arr[0] = 100

print("Original:", arr)
print("Copy:", copy_arr)

Original: [10 20 30 40 50]
Copy: [100  20  30  40  50]


In [38]:
# view() original array ka view/reference banata hai. Isliye view mein change karoge to original bhi change ho jayega.
arr = np.array([10, 20, 30, 40, 50])

view_arr = arr.view()

view_arr[0] = 100

print("Original:", arr)
print("View:", view_arr)

Original: [100  20  30  40  50]
View: [100  20  30  40  50]


In [39]:
# Array Iterating
# Array ke har element ko one-by-one access karna iteration hai.
arr = np.array([10, 20, 30, 40, 50])

for value in arr:
    print(value)

10
20
30
40
50


In [40]:
arr_2d = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

for row in arr_2d:
    print(row)

[10 20 30]
[40 50 60]


In [41]:
# Agar har individual element print karna ho:
for row in arr_2d:
    for value in row:
        print(value)

10
20
30
40
50
60


In [42]:
# NumPy multidimensional arrays ko iterate karne ke liye nditer() bhi provide karta hai:
for value in np.nditer(arr_2d):
    print(value)

10
20
30
40
50
60


In [43]:
# Array Join
# Do arrays ko combine karne ke liye np.concatenate()
arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])

joined = np.concatenate((arr1, arr2))

print(joined)

[10 20 30 40 50 60]


In [44]:
# axis=0 — rows ke neeche rows
arr1 = np.array([
    [10, 20],
    [30, 40]
])

arr2 = np.array([
    [50, 60],
    [70, 80]
])

joined = np.concatenate((arr1, arr2), axis=0)

print(joined)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [45]:
# axis=1— rows ke neeche column
arr1 = np.array([
    [10, 20],
    [30, 40]
])

arr2 = np.array([
    [50, 60],
    [70, 80]
])

joined = np.concatenate((arr1, arr2), axis=1)

print(joined)

[[10 20 50 60]
 [30 40 70 80]]


In [46]:
# Array Split
arr = np.array([10, 20, 30, 40, 50, 60])
split_arr = np.array_split(arr, 3)
# daary divide in parts
print(split_arr)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [47]:
arr = np.array([10, 20, 30, 40, 50, 60])

split_arr = np.array_split(arr, 2)

print(split_arr)

[array([10, 20, 30]), array([40, 50, 60])]


In [48]:
# Array Search
# . where() — value ka index find karna
arr = np.array([10, 20, 30, 40, 50, 30])

result = np.where(arr == 30)

print(result)

(array([2, 5]),)


In [49]:
result = np.where(arr > 20)

print(result)

(array([2, 3, 4, 5]),)


In [50]:
arr = np.array([10, 20, 30, 40, 50])
# value search in sorted array
result = np.searchsorted(arr, 35)

print(result)

3


In [51]:
arr = np.array([10, 20, 30, 40, 50, 30])

print(np.where(arr == 30))
print(np.where(arr > 20))

(array([2, 5]),)
(array([2, 3, 4, 5]),)


In [52]:
arr = np.array([50, 10, 40, 20, 30])
# arr ko sort karna
sorted_arr = np.sort(arr)

print(sorted_arr)

[10 20 30 40 50]


In [53]:
print("Original:", arr)
print("Sorted:", sorted_arr)

Original: [50 10 40 20 30]
Sorted: [10 20 30 40 50]


In [54]:
arr_2d = np.array([
    [30, 10, 20],
    [60, 40, 50]
])

print(np.sort(arr_2d))

[[10 20 30]
 [40 50 60]]


In [55]:
# Array Filtering
# Filtering ka matlab hai condition ke basis par array se specific values nikalna.
arr = np.array([10, 20, 30, 40, 50])
filter_arr = arr > 30

print(filter_arr)

[False False False  True  True]


In [56]:
new_arr = arr[arr >= 20]

print(new_arr)

[20 30 40 50]


In [57]:
new_arr = arr[arr % 2 == 0]

print(new_arr)

[10 20 30 40 50]


In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("Online_Retail_Cleaned.csv")
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

revenue = df["Revenue"].values

In [4]:
print("Mean:", np.mean(revenue))
print("Maximum:", np.max(revenue))
print("Minimum:", np.min(revenue))
print("Standard Deviation:", np.std(revenue))

Mean: 22.629194702748947
Maximum: 168469.6
Minimum: 0.0
Standard Deviation: 311.0830688527621
